apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU1TVRjNE1UTTBOekFlRncweU1EQTJNVEF3T1RJNU1EZGFGdzB6TURBMk1EZ3dPVEk1TURkYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU1TVRjNE1UTTBOekJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkJNeGNTQWthS1c1aWw5d3ExNkV2OEo4T3VWWTJPdUtYb205RlIwdmFKZVgKNnFhaklHUURxSklCaEhJL1dNelpJYzFvRDNDdlFDdDY3S3FKbHN0VmpCS2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEMHBIZlpBSUhmCk82aW9LUEFyZ282djNpOHAxbDRLUGpqc2I0VThkUVAvalFJZ1dwVngzL2l1c0pqVms3WlNhQTNxWVcwU1gyS1YKUHdscERRVDRmcWY2SEpFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://10.100.28.2:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: d5230e805acea1a0f4492314df819a96
    username: admin
